version: '3.5'
services:
  ztncui:
    image: keynetworks/ztncui
    container_name: ztncui
    restart: unless-stopped
    ports:
      - 9993:9993
      - 9993:9993/udp
      - 3443:3443
    volumes:
      - ./data/zerotier:/var/lib/zerotier-one
      - ./data/ztncui:/opt/key-networks/ztncui/etc
    environment:
      - ENDPOINT=${ZTNCUI_ENDPOINT:-localhost/9993}
      - HTTPS_PORT=3443
      - HTTP_ALL_INTERFACES=yes
      - ZTNCUI_PASSWD=${ZTNCUI_PASSWORD}
    profiles:
      - vpn